// Verified action map mapping [appTarget] -> [userIntent] -> [Composio Slugs]
export const COMPOSIO_ACTION_MAP: Record<string, Record<string, string[]>> = {
  'gmail': {
    'default': [
      'GOOGLESUPER_FETCH_EMAILS',
      'GOOGLESUPER_SEND_EMAIL',
      'GOOGLESUPER_CREATE_EMAIL_DRAFT',
      'GOOGLESUPER_SEND_DRAFT',
      'GOOGLESUPER_REPLY_TO_THREAD'
    ],
    'send': ['GOOGLESUPER_SEND_EMAIL', 'GOOGLESUPER_CREATE_EMAIL_DRAFT'],
    'read': ['GOOGLESUPER_FETCH_EMAILS', 'GOOGLESUPER_GET_DRAFT', 'GOOGLESUPER_LIST_DRAFTS'],
    'search': ['GOOGLESUPER_FETCH_EMAILS'],
  },
  'googlecalendar': {
    'default': [
      'GOOGLESUPER_CREATE_EVENT',
      'GOOGLESUPER_DELETE_EVENT',
      'GOOGLESUPER_EVENTS_LIST',
      'GOOGLESUPER_LIST_CALENDARS',
      'GOOGLESUPER_UPDATE_EVENT',
      'GOOGLESUPER_PATCH_EVENT'
    ],
    'create': ['GOOGLESUPER_CREATE_EVENT'],
    'read': ['GOOGLESUPER_EVENTS_LIST', 'GOOGLESUPER_LIST_CALENDARS'],
    'update': ['GOOGLESUPER_UPDATE_EVENT', 'GOOGLESUPER_PATCH_EVENT'],
  },
  'googlesheets': {
    'default': [
      'GOOGLESUPER_CREATE_GOOGLE_SHEET1',
      'GOOGLESUPER_SPREADSHEETS_VALUES_APPEND',
      'GOOGLESUPER_VALUES_GET',
      'GOOGLESUPER_BATCH_UPDATE',
      'GOOGLESUPER_GET_SHEET_NAMES',
      'GOOGLESUPER_GET_SPREADSHEET_INFO'
    ],
    'create': ['GOOGLESUPER_CREATE_GOOGLE_SHEET1'],
    'write': ['GOOGLESUPER_SPREADSHEETS_VALUES_APPEND', 'GOOGLESUPER_BATCH_UPDATE'],
    'read': ['GOOGLESUPER_VALUES_GET', 'GOOGLESUPER_GET_SHEET_NAMES'],
  },
  'googledrive': {
    'default': [
      'GOOGLESUPER_FIND_FILE',
      'GOOGLESUPER_FIND_FOLDER',
      'GOOGLESUPER_DOWNLOAD_FILE',
      'GOOGLESUPER_CREATE_FILE',
      'GOOGLESUPER_CREATE_FOLDER',
      'GOOGLESUPER_COPY_FILE',
      'GOOGLESUPER_DELETE_FILE'
    ],
  },
  'googletasks': {
    'default': [
      'GOOGLESUPER_INSERT_TASK',
      'GOOGLESUPER_LIST_TASKS',
      'GOOGLESUPER_LIST_TASK_LISTS',
      'GOOGLESUPER_UPDATE_TASK',
      'GOOGLESUPER_DELETE_TASK',
      'GOOGLESUPER_PATCH_TASK'
    ],
  },
  'spotify': {
    'default': [
      'SPOTIFY_START_RESUME_PLAYBACK',
      'SPOTIFY_PAUSE_PLAYBACK',
      'SPOTIFY_GET_CURRENTLY_PLAYING_TRACK',
      'SPOTIFY_GET_THE_USER_S_QUEUE',
      'SPOTIFY_GET_CURRENT_USER_S_PLAYLISTS',
      'SPOTIFY_ADD_ITEM_TO_PLAYBACK_QUEUE',
      'SPOTIFY_GET_AVAILABLE_DEVICES',
      'SPOTIFY_CREATE_PLAYLIST',
      'SPOTIFY_ADD_ITEMS_TO_PLAYLIST'
    ],
  },
  'todoist': {
    'default': [
      'TODOIST_CREATE_TASK',
      'TODOIST_GET_TASK',
      'TODOIST_GET_ALL_TASKS',
      'TODOIST_DELETE_TASK',
      'TODOIST_CREATE_PROJECT',
      'TODOIST_GET_ALL_PROJECTS'
    ],
  },
  'notion': {
    'default': [
      'NOTION_CREATE_NOTION_PAGE',
      'NOTION_INSERT_ROW_DATABASE',
      'NOTION_APPEND_TEXT_BLOCKS',
      'NOTION_QUERY_DATABASE',
      'NOTION_FETCH_DATA'
    ],
  },
  'slackbot': {
    'default': [
      'SLACKBOT_CREATE_CHANNEL',
      'SLACKBOT_INVITE_USERS_TO_A_CHANNEL',
      'SLACKBOT_DELETES_A_MESSAGE_FROM_A_CHAT',
      'SLACK_CHAT_POST_MESSAGE',
      'SLACK_LIST_UNREAD_CHANNEL_MESSAGES'
    ],
  },
  'slack': {
    'default': [
      'SLACK_CREATE_CHANNEL',
      'SLACK_CHAT_POST_MESSAGE',
      'SLACK_DELETES_A_MESSAGE_FROM_A_CHAT',
      'SLACK_LIST_UNREAD_CHANNEL_MESSAGES',
      'SLACK_INVITE_USER_TO_CHANNEL'
    ],
  },
  'microsoftteams': {
    'default': [
      'MICROSOFT_TEAMS_CREATE_CHANNEL',
      'MICROSOFT_TEAMS_CHATS_GET_ALL_CHATS',
      'MICROSOFT_TEAMS_CHATS_GET_ALL_MESSAGES',
      'MICROSOFT_TEAMS_ADD_TEAM_MEMBER',
      'MICROSOFT_TEAMS_TEAMS_LIST_CHANNELS',
      'MICROSOFT_TEAMS_LIST_MESSAGE_REPLIES'
    ],
  },
  'onedrive': {
    'default': [
      'ONE_DRIVE_DOWNLOAD_FILE',
      'ONE_DRIVE_ONEDRIVE_FIND_FILE',
      'ONE_DRIVE_LIST_ALL_DRIVE_ITEMS',
      'ONE_DRIVE_SEARCH_DRIVE_ITEMS',
      'ONE_DRIVE_GET_ITEM',
      'ONE_DRIVE_DELETE_ITEM'
    ],
  },
  'github': {
    'default': [
      'GITHUB_ADD_ASSIGNEES_TO_AN_ISSUE',
      'GITHUB_ADD_LABELS_TO_AN_ISSUE',
      'GITHUB_ADD_SUB_ISSUE',
      'GITHUB_APPROVE_WORKFLOW_RUN_FOR_FORK_PULL_REQUEST',
      'GITHUB_CREATE_ISSUE',
      'GITHUB_FIND_PULL_REQUESTS',
      'GITHUB_FIND_REPOSITORIES'
    ],
  },
  'search': {
    'default': [
      'EXA_SEARCH',
      'EXA_ANSWER',
      'EXA_GET_CONTENTS_ACTION',
      'EXA_FIND_SIMILAR'
    ]
  }
};
